### ISSUE TITLE
Webpack issue

### ISSUE THREAD

**Issue by gendronb** [fgpv-vpgf/contributed-plugins#121]
Hello all,

I have issue when trying to build or start dev server for the range-slider plugin (master branch) :

**Steps to reproduce :** 

- clone repo

on master branch :

- `cd` into range-slider
- run `npm install`
- run `npm build`

**Output :**

```
> range-slider@0.1.0 build C:\data\dev\nrcan\contributed-plugins\range-slider
> webpack --mode=production --config=webpack.config.js && npm run sass

(node:23396) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was mo
ved to NormalModule.getCompilationHooks(compilation).loader
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:23396) [DEP_WEBPACK_MAIN_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: MainTemplate.hooks.renderManifest is deprecated (us
e Compilation.hooks.renderManifest instead)
(node:23396) [DEP_WEBPACK_CHUNK_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: ChunkTemplate.hooks.renderManifest is deprecated (
use Compilation.hooks.renderManifest instead)
(node:23396) [DEP_WEBPACK_MAIN_TEMPLATE_HASH_FOR_CHUNK] DeprecationWarning: MainTemplate.hooks.hashForChunk is deprecated (use J
avascriptModulesPlugin.getCompilationHooks().chunkHash instead)
(node:23396) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
[webpack-cli] Compilation finished
assets by status 14.8 MiB [cached] 29 assets
orphan modules 150 KiB [orphan] 97 modules
runtime modules 1.03 KiB 7 modules
cacheable modules 454 KiB
  modules by path ./node_modules/ 395 KiB
    modules by path ./node_modules/rxjs/internal/ 26.7 KiB 19 modules
    ./node_modules/nouislider/distribute/nouislider.js 89.6 KiB [built] [code generated]
    ./node_modules/rxjs/_esm5/index.js + 97 modules 154 KiB [built] [code generated]
    ./node_modules/dom-to-image/src/dom-to-image.js 26.6 KiB [built] [code generated]
    ./node_modules/gifshot/dist/gifshot.js 85.1 KiB [built] [code generated]
    ./node_modules/file-saver/FileSaver.js 5.83 KiB [built] [code generated]
    ./node_modules/detect-browser/index.js 7.34 KiB [built] [code generated]
    modules by path ./src/*.ts 59.6 KiB 5 modules
    ./src/loader.js 42 bytes [built] [code generated]
    ./src/main.scss 39 bytes [built] [code generated] [1 error]

ERROR in ./src/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: The 'compilation' argument must be an instance of Compilation
    at getCompilationHooks (C:\data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\javascript\JavascriptMod
ulesPlugin.js:119:10)
    at C:\data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\javascript\CommonJsChunkFormatPlugin.js:30:19
    at Hook.eval [as call] (eval at create (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_modules
\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_modules\tapab
le\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:987:30)
    at C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_mo
dules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
s\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_modules\tapa
ble\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:987:30)

    at C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_s\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_modules\tap
able\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:987:30
)
    at C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_
s\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_modules\ta
pable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:987:3
0)
    at C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node
s\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_modules\t
apable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:987:
s\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:987:30)
    at C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_modules\tapable\lib\H
ookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\node_modules\tapable\lib\H
ook.js:18:14)
    at Compiler.compile (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:1024:28)
    at Compiler.runAsChild (C:\Data\dev\nrcan\contributed-plugins\range-slider\node_modules\webpack\lib\Compiler.js:495:8)
 @ ./src/loader.js 2:0-21

webpack 5.11.0 compiled with 1 error in 172713 ms
(node:23396) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
(node:23396) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! range-slider@0.1.0 build: `webpack --mode=production --config=webpack.config.js && npm run sass`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the range-slider@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bruno\AppData\Roaming\npm-cache\_logs\2021-01-14T20_28_53_234Z-debug.log
```

**Comment by gendronb** [comment]
Reverting to before commit #119 fixes ths issue...

**Comment by jolevesq** [comment]
@gendronb Thanks for your input. If you have been able to fix it by reverting prior to #119 commit, it may help to find the issue.

I have deleted my node_module, redo install and build and I have no problem.
```
[webpack-cli] Compilation finished
assets by path samples/ 278 KiB 18 assets
assets by status 14.3 MiB [big] 5 assets
assets by path *.ts 12.3 KiB
  asset slider-bar.d.ts 6.22 KiB [compared for emit]
  asset template.d.ts 2.77 KiB [compared for emit]
  asset slider-manager.d.ts 2 KiB [compared for emit]
  asset slider-controls.d.ts 772 bytes [compared for emit]
  asset index.d.ts 621 bytes [compared for emit]
assets by path ./ 157 KiB
  asset ./range-slider.js 146 KiB [compared for emit] [minimized] (name: main) 1 related asset
  asset ./range-slider.css 10.9 KiB [emitted] (name: main)
Entrypoint main 157 KiB = ./range-slider.css 10.9 KiB ./range-slider.js 146 KiB
```
If you do `npm run serve` you have the same error and are not able to serve?

**Comment by gendronb** [comment]
@jolevesq I have the same issue when "serving". Looks to me like an issue with webpack v5 vs v4. Did not try to delete my node_modules because I did the first attempt with a fresh clone of he repo.

**Comment by gendronb** [comment]
Reporting for other plugins :

my-first-plugin : OK
swiper: OK

@jolevesq let me fetch a clean copy of the repo and try again to see what happens...

**Comment by jolevesq** [comment]
@gendronb This is weird. Tried again this morning but I am not able to reproduce. Everything works fine on my end. I will ask someone from my team who has not worked on this for while to see if he can update his branch to the latest code and run the application.

From the error, there is something wrong with the viewer style file. If you navigate to this path `http://127.0.0.1:6001/fgpv/rv-styles.css` from your browser, do you have access to the file? You also have a 404 for rv-main.js. Looks like the application has a hard time to access the fgpv folder inside the repo.

Have you tried it on different browsers?

**Comment by gendronb** [comment]
@jolevesq

Hmmm... will do a few more tests this morning, and keep you updated.

**Comment by jolevesq** [comment]
@gendronb Someone from my team has been able to reset his repo, rebuild and serve without problems. If you can find a solution or have more information, we will be glad to hear it. Thanks

**Comment by gendronb** [comment]
@jolevesq I did a few more tests, and they all pass now. Very weird. I will close the issue for now, and reopen if necessary. Thanks for your help.
